export const garments = [
  { icon: 'wedding',     label: 'Wedding Dresses' },
  { icon: 'prom',        label: 'Prom Dresses' },
  { icon: 'evening',     label: 'Evening Gowns' },
  { icon: 'gown',        label: 'Formal Gowns' },
  { icon: 'bridesmaid',  label: 'Bridesmaid Dresses' },
  { icon: 'dress',       label: 'Dresses' },
  { icon: 'skirt',       label: 'Skirts' },
  { icon: 'suit',        label: "Men's Suits" },
  { icon: 'suit',        label: "Women's Suits" },
  { icon: 'tux',         label: 'Tuxedos' },
  { icon: 'blazer',      label: 'Blazers' },
  { icon: 'blazer',      label: 'Sport Coats' },
  { icon: 'vest',        label: 'Vests' },
  { icon: 'dressshirt',  label: 'Dress Shirts' },
  { icon: 'blouse',      label: 'Blouses' },
  { icon: 'shirt',       label: 'Shirts' },
  { icon: 'tee',         label: 'T-Shirts' },
  { icon: 'polo',        label: 'Polo Shirts' },
  { icon: 'pants',       label: 'Pants' },
  { icon: 'dresspants',  label: 'Dress Pants' },
  { icon: 'jeans',       label: 'Jeans' },
  { icon: 'shorts',      label: 'Shorts' },
  { icon: 'coat',        label: 'Winter Coats' },
  { icon: 'jacket',      label: 'Jackets' },
  { icon: 'hoodie',      label: 'Hoodies' },
  { icon: 'sweater',     label: 'Sweaters' },
  { icon: 'uniform',     label: 'Uniforms' },
  { icon: 'uniform',     label: 'Military Uniforms' },
  { icon: 'scrubs',      label: 'Scrubs' },
  { icon: 'choir',       label: 'Choir / Performance' },
  { icon: 'cultural',    label: 'Cultural / Traditional' },
  { icon: 'leather',     label: 'Leather Items' },
  { icon: 'curtain',     label: 'Curtains' },
  { icon: 'household',   label: 'Household Sewing' },
  { icon: 'plus',        label: 'Plus More…' },
]

export const alterations = [
  { icon: 'hem',             label: 'Hemming' },
  { icon: 'hem',             label: 'Regular Hems' },
  { icon: 'hem',             label: 'Original Jean Hems' },
  { icon: 'shorten-pants',   label: 'Shorten Pants' },
  { icon: 'lengthen-pants',  label: 'Lengthen Pants' },
  { icon: 'shorten-dress',   label: 'Shorten Dresses' },
  { icon: 'shorten-dress',   label: 'Shorten Gowns' },
  { icon: 'shorten-skirt',   label: 'Shorten Skirts' },
  { icon: 'shorten-sleeves', label: 'Shorten Sleeves' },
  { icon: 'lengthen-sleeves',label: 'Lengthen Sleeves' },
  { icon: 'strap',           label: 'Shorten Straps' },
  { icon: 'strap',           label: 'Adjust Straps' },
  { icon: 'takein',          label: 'Take in Sides' },
  { icon: 'length',          label: 'Let out Sides' },
  { icon: 'takein',          label: 'Waist Take-in' },
  { icon: 'length',          label: 'Waist Let-out' },
  { icon: 'taper',           label: 'Taper Pants' },
  { icon: 'taper',           label: 'Taper Jeans' },
  { icon: 'taper',           label: 'Taper Sleeves' },
  { icon: 'shoulder',        label: 'Adjust Shoulders' },
  { icon: 'jacket-length',   label: 'Adjust Jacket Length' },
  { icon: 'shirt-length',    label: 'Adjust Shirt Length' },
  { icon: 'cuff',            label: 'Adjust Cuffs' },
  { icon: 'bodice',          label: 'Adjust Bodice' },
  { icon: 'bustle',          label: 'Add Bustles' },
  { icon: 'cups',            label: 'Add Cups / Padding' },
  { icon: 'elastic',         label: 'Replace Elastic Waistbands' },
  { icon: 'drawstring',      label: 'Replace Drawstrings' },
  { icon: 'zipper',          label: 'Replace Zippers' },
  { icon: 'zipper',          label: 'Repair Zippers' },
  { icon: 'coatzip',         label: 'Replace Coat Zippers' },
  { icon: 'pantzip',         label: 'Replace Pant Zippers' },
  { icon: 'needle',          label: 'Sew Buttons' },
  { icon: 'button',          label: 'Replace Buttons' },
  { icon: 'snap',            label: 'Replace Snaps' },
  { icon: 'hook',            label: 'Replace Hooks' },
  { icon: 'velcro',          label: 'Replace Velcro' },
  { icon: 'patch',           label: 'Repair Holes' },
  { icon: 'patch',           label: 'Patch Holes' },
  { icon: 'tear',            label: 'Repair Tears' },
  { icon: 'seam',            label: 'Repair Seams' },
  { icon: 'reinforce',       label: 'Reinforce Seams' },
  { icon: 'pocket',          label: 'Repair Pockets' },
  { icon: 'beltloop',        label: 'Repair Belt Loops' },
  { icon: 'lining',          label: 'Repair Linings' },
  { icon: 'lining',          label: 'Replace Linings' },
  { icon: 'needle',          label: 'Sew Patches' },
  { icon: 'cuff',            label: 'Repair Cuffs' },
  { icon: 'hem',             label: 'Repair Hems' },
  { icon: 'scissors',        label: 'General Repairs' },
  { icon: 'plus',            label: 'Plus More…' },
]

export const quotes = [
  {
    body: 'I brought in a 1960s wedding gown my grandmother wore. They restored the lace, took it in three sizes, and added a French bustle. It looked like it had been made for me.',
    name: 'Eleanor Park',
    role: 'Bride · 2024',
  },
  {
    body: 'I have had every suit I own taken in here for the better part of a decade. Honest pricing, honest pinning, and they never try to upsell you on work you do not need.',
    name: 'David Marquez',
    role: 'Customer since 2017',
  },
  {
    body: 'My dress blues had to be perfect for my retirement ceremony. They turned it around in three days and the chest fit like it was issued yesterday.',
    name: 'SFC Jonathan Reyes',
    role: 'U.S. Army (Ret.)',
  },
]
