export const garmentCategories = [
  {
    icon: 'wedding',
    label: 'Formal & Special Occasion Wear',
    items: ['Wedding dress', 'Prom dress', 'Bridesmaid dress', 'Gown', 'Dress', 'Skirt', 'Tuxedo', 'Vest'],
  },
  {
    icon: 'suit',
    label: 'Suits & Professional Wear',
    items: ["Men's suit", "Women's suit", 'Suit jacket', 'Blazer', 'Sport coat', 'Dress pants', 'Dress shirt', 'Blouse'],
  },
  {
    icon: 'shirt',
    label: 'Everyday Clothing',
    items: ['Pants', 'Jeans', 'Shorts', 'Shirt', 'T-shirt', 'Polo shirt', 'Hoodie', 'Sweater'],
  },
  {
    icon: 'coat',
    label: 'Outerwear',
    items: ['Coat', 'Winter coat', 'Jacket'],
  },
  {
    icon: 'uniform',
    label: 'Uniforms & Specialty Clothing',
    items: ['Military uniform', 'Work uniform', 'Scrubs', 'Choir outfit', 'Performance wear', 'Cultural / traditional clothing', 'Leather item', 'Faux leather item'],
  },
  {
    icon: 'curtain',
    label: 'Home & Specialty Sewing Items',
    items: ['Curtains', 'Simple household sewing item', 'Other'],
  },
]

export const alterationCategories = [
  {
    icon: 'hem',
    label: 'Hemming & Length Adjustments',
    items: ['Regular hem', 'Original jean hem', 'Dress hem', 'Gown hem', 'Skirt hem', 'Pant hem', 'Shorten', 'Lengthen'],
  },
  {
    icon: 'takein',
    label: 'Fit Adjustments',
    items: ['Take in', 'Let out', 'Waist adjustment', 'Side adjustment', 'Tapering', 'Sleeve adjustment', 'Strap adjustment', 'Shoulder adjustment', 'Cuff adjustment', 'Shirt length adjustment', 'Jacket length adjustment', 'Dress top / bodice adjustment'],
  },
  {
    icon: 'wedding',
    label: 'Formalwear Alterations',
    items: ['Bustle', 'Dress adjustment', 'Gown adjustment', 'Wedding dress alteration', 'Prom dress alteration', 'Bridesmaid dress alteration', 'Cups / padding'],
  },
  {
    icon: 'suit',
    label: 'Suit & Jacket Alterations',
    items: ['Jacket sleeve adjustment', 'Jacket side adjustment', 'Jacket length adjustment', 'Shoulder adjustment', 'Pant waist adjustment', 'Pant tapering', 'Suit fitting adjustment'],
  },
  {
    icon: 'zipper',
    label: 'Zippers, Buttons & Closures',
    items: ['Zipper repair', 'Zipper replacement', 'Coat zipper replacement', 'Pant zipper replacement', 'Button sewing', 'Button replacement', 'Snap replacement', 'Hook replacement', 'Velcro replacement'],
  },
  {
    icon: 'patch',
    label: 'Repairs & Patching',
    items: ['Hole repair', 'Patch repair', 'Tear repair', 'Seam repair', 'Seam reinforcement', 'Pocket repair', 'Belt loop repair', 'Cuff repair', 'Hem repair', 'Patch sewing'],
  },
  {
    icon: 'lining',
    label: 'Lining, Elastic & Small Fixes',
    items: ['Lining repair', 'Lining replacement', 'Elastic waistband replacement', 'Drawstring replacement', 'General clothing repair'],
  },
]

export const garments = [
  { icon: 'wedding',     label: 'Wedding Dresses' },
  { icon: 'prom',        label: 'Prom Dresses' },
  { icon: 'evening',     label: 'Evening Gowns' },
  { icon: 'gown',        label: 'Formal Gowns' },
  { icon: 'bridesmaid',  label: 'Bridesmaid Dresses' },
  { icon: 'dress',       label: 'Dresses' },
  { icon: 'skirt',       label: 'Skirts' },
  { icon: 'suit',        label: "Men's Suits" },
  { icon: 'suit',        label: "Women's Suits" },
  { icon: 'tux',         label: 'Tuxedos' },
  { icon: 'blazer',      label: 'Blazers' },
  { icon: 'blazer',      label: 'Sport Coats' },
  { icon: 'vest',        label: 'Vests' },
  { icon: 'dressshirt',  label: 'Dress Shirts' },
  { icon: 'blouse',      label: 'Blouses' },
  { icon: 'shirt',       label: 'Shirts' },
  { icon: 'tee',         label: 'T-Shirts' },
  { icon: 'polo',        label: 'Polo Shirts' },
  { icon: 'pants',       label: 'Pants' },
  { icon: 'dresspants',  label: 'Dress Pants' },
  { icon: 'jeans',       label: 'Jeans' },
  { icon: 'shorts',      label: 'Shorts' },
  { icon: 'coat',        label: 'Winter Coats' },
  { icon: 'jacket',      label: 'Jackets' },
  { icon: 'hoodie',      label: 'Hoodies' },
  { icon: 'sweater',     label: 'Sweaters' },
  { icon: 'uniform',     label: 'Uniforms' },
  { icon: 'uniform',     label: 'Military Uniforms' },
  { icon: 'scrubs',      label: 'Scrubs' },
  { icon: 'choir',       label: 'Choir / Performance' },
  { icon: 'cultural',    label: 'Cultural / Traditional' },
  { icon: 'leather',     label: 'Leather Items' },
  { icon: 'curtain',     label: 'Curtains' },
  { icon: 'household',   label: 'Household Sewing' },
  { icon: 'plus',        label: 'Plus More…' },
]

export const alterations = [
  { icon: 'hem',             label: 'Hemming' },
  { icon: 'hem',             label: 'Regular Hems' },
  { icon: 'hem',             label: 'Original Jean Hems' },
  { icon: 'shorten-pants',   label: 'Shorten Pants' },
  { icon: 'lengthen-pants',  label: 'Lengthen Pants' },
  { icon: 'shorten-dress',   label: 'Shorten Dresses' },
  { icon: 'shorten-dress',   label: 'Shorten Gowns' },
  { icon: 'shorten-skirt',   label: 'Shorten Skirts' },
  { icon: 'shorten-sleeves', label: 'Shorten Sleeves' },
  { icon: 'lengthen-sleeves',label: 'Lengthen Sleeves' },
  { icon: 'strap',           label: 'Shorten Straps' },
  { icon: 'strap',           label: 'Adjust Straps' },
  { icon: 'takein',          label: 'Take in Sides' },
  { icon: 'length',          label: 'Let out Sides' },
  { icon: 'takein',          label: 'Waist Take-in' },
  { icon: 'length',          label: 'Waist Let-out' },
  { icon: 'taper',           label: 'Taper Pants' },
  { icon: 'taper',           label: 'Taper Jeans' },
  { icon: 'taper',           label: 'Taper Sleeves' },
  { icon: 'shoulder',        label: 'Adjust Shoulders' },
  { icon: 'jacket-length',   label: 'Adjust Jacket Length' },
  { icon: 'shirt-length',    label: 'Adjust Shirt Length' },
  { icon: 'cuff',            label: 'Adjust Cuffs' },
  { icon: 'bodice',          label: 'Adjust Bodice' },
  { icon: 'bustle',          label: 'Add Bustles' },
  { icon: 'cups',            label: 'Add Cups / Padding' },
  { icon: 'elastic',         label: 'Replace Elastic Waistbands' },
  { icon: 'drawstring',      label: 'Replace Drawstrings' },
  { icon: 'zipper',          label: 'Replace Zippers' },
  { icon: 'zipper',          label: 'Repair Zippers' },
  { icon: 'coatzip',         label: 'Replace Coat Zippers' },
  { icon: 'pantzip',         label: 'Replace Pant Zippers' },
  { icon: 'needle',          label: 'Sew Buttons' },
  { icon: 'button',          label: 'Replace Buttons' },
  { icon: 'snap',            label: 'Replace Snaps' },
  { icon: 'hook',            label: 'Replace Hooks' },
  { icon: 'velcro',          label: 'Replace Velcro' },
  { icon: 'patch',           label: 'Repair Holes' },
  { icon: 'patch',           label: 'Patch Holes' },
  { icon: 'tear',            label: 'Repair Tears' },
  { icon: 'seam',            label: 'Repair Seams' },
  { icon: 'reinforce',       label: 'Reinforce Seams' },
  { icon: 'pocket',          label: 'Repair Pockets' },
  { icon: 'beltloop',        label: 'Repair Belt Loops' },
  { icon: 'lining',          label: 'Repair Linings' },
  { icon: 'lining',          label: 'Replace Linings' },
  { icon: 'needle',          label: 'Sew Patches' },
  { icon: 'cuff',            label: 'Repair Cuffs' },
  { icon: 'hem',             label: 'Repair Hems' },
  { icon: 'scissors',        label: 'General Repairs' },
  { icon: 'plus',            label: 'Plus More…' },
]

export const quotes = [
  {
    body: 'I brought in a 1960s wedding gown my grandmother wore. They restored the lace, took it in three sizes, and added a French bustle. It looked like it had been made for me.',
    name: 'Eleanor Park',
    role: 'Bride · 2024',
  },
  {
    body: 'I have had every suit I own taken in here for the better part of a decade. Honest pricing, honest pinning, and they never try to upsell you on work you do not need.',
    name: 'David Marquez',
    role: 'Customer since 2017',
  },
  {
    body: 'My dress blues had to be perfect for my retirement ceremony. They turned it around in three days and the chest fit like it was issued yesterday.',
    name: 'SFC Jonathan Reyes',
    role: 'U.S. Army (Ret.)',
  },
]
